import Logo from './components/Logo';
import Navigation from './components/navigation';

export const metadata = {
    title: 'Booking App',
    description: 'Generated by Booking App',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <header>
                    <Logo />
                    <Navigation />
                </header>
                <main>{children}</main>
                <footer>Copyright</footer>
            </body>
        </html>
    );
}
