export const metadata = {
    title: 'Booking App',
    description: 'Generated by Booking App',
};
import Navigation from './components/navigation';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navigation />
                <main>{children}</main>
            </body>
        </html>
    );
}
